version: '3'
services:
  bridge:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: senither/hypixel-discord-chat-bridge
    environment:
      SERVER_HOST: mc.hypixel.net
      SERVER_PORT: 25565
      MINECRAFT_USERNAME: xSkyrea_
      MINECRAFT_PASSWORD: DxKii7512*
      MINECRAFT_LOBBY_HOLDER: lobbyHolder
      MINECRAFT_ACCOUNT_TYPE: microsoft
      DISCORD_TOKEN: 758339903712264232
      DISCORD_CHANNEL: 981021453065535538
      DISCORD_COMMAND_ROLE: 981022330971099136
      DISCORD_OWNER_ID: 584155097291030528
      MESSAGE_MODE: bot
      EXPRESS_ENABLED: false
      EXPRESS_PORT: 8880
      EXPRESS_AUTHORIZATION: authorizationHeaderString
